#!/bin/bash
ROOT="$(pwd)/$(dirname "$0")"
mkdir -p "${ROOT}/embeddings"
mkdir -p "${ROOT}/models"
mkdir -p "${ROOT}/log"
docker run -d --name faiss-image-server -it -p 50051:50051 -u `id -u $USER` \
         -v "${ROOT}/embeddings":/app/embeddings \
         -v "${ROOT}/models":/app/models \
         -v "${ROOT}/log":/app/log \
         daangn/faiss-image-server server.py --log log/faiss_image_server.log \
           --rails_env "$ENV"
